version: 2.1

orbs:
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/mailpace/gomailpace
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Run tests and collect coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload


workflows:
  version: 2
  build:
    jobs:
      - build
